services:
  kopia:
      image: yanik39/kopia-ubuntu:latest
      container_name: Kopia-Ubuntu
      user: "0:0"
      restart: "unless-stopped"
      privileged: true
      cap_add:
        - SYS_ADMIN
      security_opt:
        - apparmor:unconfined
      devices:
        - /dev/fuse:/dev/fuse:rwm
      command:
        - server
        - start
        - --disable-csrf-token-checks
        - --tls-cert-file=/data/home/XXX/ssl-certs/fullchain.pem
        - --tls-key-file=/data/home/XXX/ssl-certs/privkey.pem
        - --address=0.0.0.0:51515
        - --server-username=XXX
        - --server-password=XXX
      volumes:
        - /mnt/kopia:/tmp:shared
        - /home/XXX/docker/Kopia-Ubuntu/config:/app/config
        - /home/XXX/docker/Kopia-Ubuntu/cache:/app/cache
        - /home/XXX/docker/Kopia-Ubuntu/logs:/app/logs
        - /:/data:ro
      environment:
        KOPIA_PASSWORD: XXX
        TZ: Europe/Berlin
        USER: XXX
